const API_BASE_URL = import.meta.env.VITE_API_BASE_URL;
const API_IMAGE_URL = API_BASE_URL + import.meta.env.VITE_API_IMAGE_URL;

const IMAGES_50_URL=API_IMAGE_URL + '/50_';
const IMAGES_100_URL=API_IMAGE_URL + '/100_';
const IMAGES_200_URL=API_IMAGE_URL + '/200_';
const IMAGES_400_URL=API_IMAGE_URL + '/400_';
const IMAGES_800_URL=API_IMAGE_URL + '/800_';
const IMAGES_1200_URL=API_IMAGE_URL + '/1200_';

const APP_ENV = {
    API_BASE_URL,
    IMAGES_50_URL,
    IMAGES_100_URL,
    IMAGES_200_URL,
    IMAGES_400_URL,
    IMAGES_800_URL,
    IMAGES_1200_URL,
}

export {APP_ENV}